services:
  gateway-service:
    image: ghcr.io/nhnacademy-aiot2-lucky7/gateway-service:latest
    container_name: team1-gateway-service
    ports:
      - "10241:10241"
    env_file:
      - .env.gateway-service
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true