services:
  auth-service:
    image: ghcr.io/nhnacademy-aiot2-lucky7/auth-service:latest
    container_name: team1-auth-service
    ports:
      - "10234:10234"
    env_file:
      - .env.auth
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true