version: '3.8'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: aiot2-team1-node-red
    ports:
      - "10236:1880"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: aiot2-team1-prometheus
    ports:
      - "10237:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: aiot2-team1-grafana
    ports:
      - "10238:3000"
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    network_mode: "host"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: aiot2-team1-redis
    ports:
      - "10240:6379"
    command: redis-server --appendonly yes
    restart: unless-stopped
