services:
  influxdb:
    image: influxdb:2.7
    container_name: team1_influxdb
    ports:
      - "10236:8086"
    volumes:
      - team1-influxdb-storage:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: my-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-auth-token
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.4.3
    container_name: team1_grafana
    ports:
      - "10237:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_ADMIN_PASSWORD=admin1234
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - influxdb
    volumes:
      - team1-grafana-storage:/var/lib/grafana
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: team1_broker
    ports:
      - "10240:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    restart: unless-stopped
