services:
  aiot-data-handler:
    image: ghcr.io/nhnacademy-aiot2-lucky7/ai-analysis-result-service:latest
    container_name: team1-ai-analysis-result-service
    ports:
      - "10247:10247"
    env_file:
      - .env.ai-analysis-result
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true