services:
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: team1-broker
    ports:
      - "10240:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    restart: unless-stopped
    networks:
      - team1-net

networks:
  team1-net:
    external: true