services:
  server-resource-service:
    image: ghcr.io/nhnacademy-aiot2-lucky7/server-resource-service:latest
    container_name: team1-server-resource-service
    ports:
      - "10244:10244"
    env_file:
      - .env.server-resource-service
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true