services:
  sensor-service:
    image: ghcr.io/nhnacademy-aiot2-lucky7/data-handler:latest
    container_name: team1-data-handler
    ports:
      - "10242:10242"
    env_file:
      - .env.data-handler
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true