services:
  eureka:
    image: ghcr.io/nhnacademy-aiot2-lucky7/eureka:latest
    container_name: team1-eureka
    ports:
      - "10233:10233"
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true