services:
  rule-engine-service:
    image: ghcr.io/nhnacademy-aiot2-lucky7/rule-engine-service:latest
    container_name: team1-auth-service
    ports:
      - "10245:10245"
    env_file:
      - .env.rule-engine
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true