# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: upload file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "common_infra/nginx/*"  # nginx 설정 파일 경로
          target: "~/nginx/"              # 원격 서버에서 nginx 관련 설정 파일을 저장할 경로
          rm: false

      # Restart nginx to apply new configuration
      - name: Restart nginx to apply new configuration
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            # Backup the old nginx config (optional)
            sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
            sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
            
            # Copy new nginx configuration from uploaded files
            
            sudo cp ~/nginx/* /etc/nginx/

            # Restart nginx to apply new configuration
            sudo systemctl restart nginx

            # Optionally, check nginx configuration and reload instead of restart
            sudo nginx -t && sudo systemctl reload nginx