name: Deploy Nginx Config

on:
  push:
    branches: [main]
    paths:
      - 'nginx/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy nginx configs to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "nginx/*"
          target: "/frontend-dist"

#      - name: Reload Nginx
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.REMOTE_HOST }}
#          username: ${{ secrets.REMOTE_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          port: ${{ secrets.REMOTE_PORT }}
#          script: |
#            sudo nginx -t && sudo systemctl reload nginx