services:
  event-service:
    image: ghcr.io/nhnacademy-aiot2-lucky7/event-service:latest
    container_name: team1-event-service
    ports:
      - "10239:10239"
    env_file:
      - .env.event
    volumes:
      - ./logs:/logs
    networks:
      - team1-net

networks:
  team1-net:
    external: true